#!/usr/bin/env python3
"""
Regenerate the .po catalogues from the strings actually present in the source.

Rationale: the catalogues had drifted badly (82 strings missing, 32 stale) because
they were maintained by hand. This script derives the msgid list from the code via
extract_strings.py and pairs it with the Russian map below, so the catalogues
cannot silently fall out of step again.

Usage:
    python3 update_translations.py        # rewrite locale/{en,ru}/.../*.po
    python3 update_translations.py --check # report drift, write nothing
    python3 compile_translations.py       # then build the .mo files

Any msgid without an entry in RU is written with an empty msgstr, which makes
gettext fall back to the English text rather than showing nothing.
"""
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from extract_strings import extract_source_strings, parse_po, po_escape

LOCALE_DIR = Path(__file__).parent / 'locale'
DOMAIN = 'DirectoryObjectMigrator'

HEADER = '''# Directory Objects Migrator - {lang_name} translation
# Generated by update_translations.py; edit the RU map in that script, not this file.
msgid ""
msgstr ""
"Project-Id-Version: DirectoryObjectMigrator 1.0\\n"
"POT-Creation-Date: {date}\\n"
"Language: {lang}\\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\\n"
'''

# English msgid -> Russian msgstr
RU = {}

# --- Menus, windows, common actions ---
RU.update({
    'Directory Objects Migrator': 'Миграция объектов каталога',
    'Welcome': 'Добро пожаловать',
    'File': 'Файл',
    'Settings': 'Настройки',
    'Language': 'Язык',
    'Exit': 'Выход',
    'Help': 'Справка',
    'About': 'О программе',
    'Close': 'Закрыть',
    'Cancel': 'Отмена',
    'Save': 'Сохранить',
    'Error': 'Ошибка',
    'Info': 'Информация',
    'Success': 'Готово',
    'Version': 'Версия',
    'Features': 'Возможности',
    'Log': 'Журнал',
    'Ready': 'Готов',
    'Summary': 'Сводка',
    'Progress': 'Прогресс',
    'Notes': 'Примечания',
    'Migration tool for Active Directory objects':
        'Инструмент для миграции объектов Active Directory',
    'Change Language': 'Смена языка',
    'Language will be changed after application restart. Restart now?':
        'Язык изменится после перезапуска приложения. Перезапустить сейчас?',
})

# --- Connection settings ---
RU.update({
    'Connection': 'Подключение',
    'Connection Settings': 'Настройки подключения',
    'Connection Status': 'Состояние подключения',
    'Source DC': 'Исходный контроллер домена',
    'Destination DC': 'Целевой контроллер домена',
    'Host / IP Address:': 'Хост / IP-адрес:',
    'Port:': 'Порт:',
    'Domain:': 'Домен:',
    'Username': 'Имя пользователя',
    'Username:': 'Имя пользователя:',
    'Password': 'Пароль',
    'Password:': 'Пароль:',
    'Use TLS': 'Использовать TLS',
    'Test Connection': 'Проверить подключение',
    'Connection successful': 'Подключение установлено',
    'Connection failed': 'Не удалось подключиться',
    'Connection cancelled': 'Подключение отменено',
    'Not connected': 'Нет подключения',
    'Not configured': 'Не настроено',
    'Settings saved successfully': 'Настройки сохранены',
    'Switch to Source or Destination tab to test':
        'Для проверки перейдите на вкладку исходного или целевого контроллера',
    'Please fill in all Source DC fields':
        'Заполните все поля исходного контроллера домена',
    'Please fill in all Destination DC fields':
        'Заполните все поля целевого контроллера домена',
    'Please fill in all connection fields': 'Заполните все поля подключения',
    'Please configure connections first': 'Сначала настройте подключения',
    'Username is not configured': 'Имя пользователя не указано',
    'Password cannot be empty': 'Пароль не может быть пустым',
    'Cannot restart while a migration is running.':
        'Нельзя перезапустить приложение во время миграции.',
})

# --- Migration options ---
RU.update({
    'Migration Options': 'Параметры миграции',
    'Migration Settings': 'Настройки миграции',
    'Performance': 'Производительность',
    'Batch Size:': 'Размер пакета:',
    'Password Policy': 'Политика паролей',
    'Random Password': 'Случайный пароль',
    'Fixed Password': 'Заданный пароль',
    'Enter fixed password': 'Введите пароль',
    'Length:': 'Длина:',
    'Please enter fixed password or choose random mode':
        'Введите пароль или выберите режим случайного пароля',
    'Base DN for Migration': 'Базовый DN для миграции',
    'Base DN': 'Базовый DN',
    'Dry Run Mode': 'Режим симуляции',
    'simulation without creating objects': 'проверка без создания объектов',
    'Please specify Base DN': 'Укажите базовый DN',
})

# --- Analysis and preview ---
RU.update({
    'Analyze': 'Анализ',
    'Analyzing...': 'Выполняется анализ...',
    'Analysis': 'Анализ',
    'Analysis complete': 'Анализ завершён',
    'Analysis failed': 'Анализ завершился с ошибкой',
    'Please run analysis first': 'Сначала выполните анализ',
    'Migration Preview': 'Предпросмотр миграции',
    'Planned actions': 'Планируемые действия',
    'Objects found': 'Найденные объекты',
    'Object': 'Объект',
    'Object Type': 'Тип объекта',
    'Type': 'Тип',
    'Count': 'Количество',
    'Action': 'Действие',
    'Attribute': 'Атрибут',
    'Status': 'Состояние',
    'Source': 'Источник',
    'Source DN': 'DN в источнике',
    'Destination': 'Назначение',
    'Destination DN': 'DN в назначении',
    'Referenced object': 'Целевой объект ссылки',
    'Total objects': 'Всего объектов',
    'Mode': 'Режим',
    'Live migration': 'Реальная миграция',
    'Dry run - nothing will be written': 'Симуляция — запись не производится',
    'Start Dry Run': 'Запустить симуляцию',
    'Ready to migrate': 'Готов к миграции',
    'Destination was not checked': 'Целевой домен не проверялся',
    'These are source counts only. Existing objects and conflicts are not reflected here.':
        'Показаны только данные источника. Существующие объекты и конфликты здесь не учтены.',
    # Explanations for an empty plan. A single "everything is already migrated"
    # message used to cover every case and actively misled when a scope had simply
    # been filtered out by the ignore rules.
    'Nothing to create': 'Создавать нечего',
    'Nothing found': 'Ничего не найдено',
    'every object in this scope has already been migrated.':
        'все объекты в этой области уже перенесены.',
    'the specified DN contains no objects. Check the Base DN.':
        'по указанному DN нет объектов. Проверьте базовый DN.',
    'every object in this scope is in conflict, see above.':
        'все объекты в этой области в состоянии конфликта, см. выше.',
    'all objects found were filtered out': 'все найденные объекты отфильтрованы',
    'ignored': 'игнорируется',
    'unsupported': 'не поддерживается',
    "Built-in containers and computer accounts are skipped by design; see the 'Objects found' tab.":
        'Встроенные контейнеры и учётные записи компьютеров пропускаются намеренно; '
        'см. вкладку «Найденные объекты».',
    'no object in this scope is eligible for migration.':
        'ни один объект в этой области не подлежит переносу.',
})

# --- Object types ---
RU.update({
    'Organizational Units': 'Подразделения',
    'Users': 'Пользователи',
    'Groups': 'Группы',
    'Contacts': 'Контакты',
    'Unsupported': 'Неподдерживаемые',
    'Ignored': 'Игнорируемые',
})

# --- Statuses (also used as plan action labels) ---
RU.update({
    'CREATE': 'СОЗДАТЬ',
    'EXISTS': 'СУЩЕСТВУЕТ',
    'CONFLICT': 'КОНФЛИКТ',
    'DEFERRED': 'ОТЛОЖЕНО',
    'ERROR': 'ОШИБКА',
    'SKIPPED': 'ПРОПУЩЕНО',
})

# --- Deferred references ---
RU.update({
    'Deferred references': 'Отложенные ссылки',
    'Target not migrated yet': 'Целевой объект ещё не перенесён',
    'references pointing outside the migration scope.':
        'ссылки на объекты за пределами области миграции.',
    'can be added now; the rest need their target migrated first, then re-run this DN.':
        'можно добавить сейчас; для остальных сначала перенесите целевые объекты, '
        'затем повторите запуск для этого DN.',
    'these objects already exist in the destination but are not tracked in the migration database. They will NOT be overwritten.':
        'эти объекты уже есть в целевом домене, но отсутствуют в базе миграции. '
        'Они НЕ будут перезаписаны.',
    'could not be classified (missing objectGUID or unreadable destination). They will be skipped and logged.':
        'не удалось классифицировать (нет objectGUID или недоступен целевой домен). '
        'Они будут пропущены с записью в журнал.',
    'Users are created disabled with a generated password. Set final passwords and enable the accounts afterwards.':
        'Пользователи создаются отключёнными со случайным паролем. После миграции '
        'задайте пароли и включите учётные записи.',
    'Dry run: the destination directory will not be modified.':
        'Симуляция: целевой каталог изменён не будет.',
})

# --- Migration run ---
RU.update({
    'Start Migration': 'Начать миграцию',
    'Migration in progress': 'Выполняется миграция',
    'Initializing...': 'Инициализация...',
    'Phase': 'Этап',
    'Creating OUs': 'Создание подразделений',
    'Creating objects': 'Создание объектов',
    'Copying attributes': 'Копирование атрибутов',
    'Resolving references': 'Разрешение ссылок',
    'Verification': 'Проверка',
    'Migration completed successfully': 'Миграция успешно завершена',
    'Migration failed': 'Миграция завершилась с ошибкой',
    'Migration cancelled': 'Миграция отменена',
    'Cancel Migration': 'Отмена миграции',
    'Cancelling...': 'Отмена...',
    'Migration cancellation requested': 'Запрошена отмена миграции',
    'Are you sure you want to cancel the migration?':
        'Действительно отменить миграцию?',
})

# --- Reports ---
RU.update({
    'Generate Report': 'Создать отчёт',
    'Report Generated': 'Отчёт создан',
    'Report generated': 'Отчёт создан',
    'Open report': 'Открыть отчёт',
    'Failed to generate report': 'Не удалось создать отчёт',
    'No migration run to report on': 'Нет запусков миграции для отчёта',
    'Generate HTML report?\n(No = generate text report)':
        'Создать отчёт в формате HTML?\n(Нет — текстовый отчёт)',
    'Clear Log': 'Очистить журнал',
    'Log cleared': 'Журнал очищен',
})

# --- Migration database maintenance ---
RU.update({
    'Migration Database': 'База данных миграции',
    'Reset Database': 'Сбросить базу данных',
    'Compact': 'Компактизация',
    'Migration runs': 'Запусков миграции',
    'Tracked objects': 'Объектов в базе',
    'Pending references': 'Отложенных ссылок',
    'Database is already empty.': 'База данных уже пуста.',
    'Could not read the migration database':
        'Не удалось прочитать базу данных миграции',
    'Failed to reset the database': 'Не удалось сбросить базу данных',
    'Failed to compact the database': 'Не удалось выполнить компактизацию базы данных',
    'This will delete the entire migration history:':
        'Будет удалена вся история миграции:',
    'Objects already created in the destination domain will no longer be recognised as migrated, and the next run will report them as CONFLICT. Nothing is deleted from either domain controller.':
        'Объекты, уже созданные в целевом домене, перестанут определяться как '
        'перенесённые, и при следующем запуске будут показаны как КОНФЛИКТ. '
        'Из контроллеров доменов ничего не удаляется.',
    'A backup copy will be created first. Continue?':
        'Сначала будет создана резервная копия. Продолжить?',
    'Migration history cleared': 'История миграции очищена',
    'Backup saved to:': 'Резервная копия сохранена в:',
    'rows': 'строк',
    'Migration database was reset': 'База данных миграции сброшена',
    'Reset: clears the migration history so the next run starts from scratch. Neither domain controller is touched: objects already created in the destination remain, but will be reported as CONFLICT instead of EXISTS. A backup copy is made first.':
        'Сброс: очищает историю миграции, чтобы следующий запуск начался с нуля. '
        'Контроллеры доменов не затрагиваются: объекты, уже созданные в целевом '
        'домене, останутся, но будут показаны как КОНФЛИКТ, а не СУЩЕСТВУЕТ. '
        'Сначала создаётся резервная копия.',
    'Compact: reclaims unused space and defragments the database file. Safe to run anytime; does not delete migration history.':
        'Компактизация: освобождает неиспользуемое место и дефрагментирует файл '
        'базы данных. Безопасна в любой момент; не удаляет историю миграции.',
    'Database compacted successfully.': 'Компактизация базы данных выполнена успешно.',
    'Size before: {before}\nSize after: {after}\nFreed: {freed}':
        'Размер до: {before}\nРазмер после: {after}\nОсвобождено: {freed}',
    'Database is already compact ({size}).':
        'База данных уже компактна ({size}).',
})


def build_catalogue(lang: str, lang_name: str, msgids) -> str:
    lines = [HEADER.format(
        lang=lang,
        lang_name=lang_name,
        date=datetime.now().strftime('%Y-%m-%d %H:%M%z') or datetime.now().strftime('%Y-%m-%d %H:%M'),
    )]

    for msgid in sorted(msgids):
        if lang == 'en':
            # The msgid already is the English text; make it explicit
            msgstr = msgid
        else:
            msgstr = RU.get(msgid, '')
        lines.append(f'msgid "{po_escape(msgid)}"')
        lines.append(f'msgstr "{po_escape(msgstr)}"')
        lines.append('')

    return '\n'.join(lines)


def main():
    check_only = '--check' in sys.argv
    msgids = extract_source_strings()

    untranslated = sorted(m for m in msgids if m not in RU)
    print(f"strings in source: {len(msgids)}")
    print(f"russian entries:   {len(RU)}")
    print(f"untranslated:      {len(untranslated)}")

    if untranslated:
        print("\n  no Russian text for (will fall back to English):")
        for text in untranslated:
            print(f"    {text!r}")

    stale = sorted(k for k in RU if k not in msgids)
    if stale:
        print(f"\n  RU entries no longer referenced in source: {len(stale)}")
        for text in stale:
            print(f"    {text!r}")

    if check_only:
        return 1 if untranslated or stale else 0

    for lang, lang_name in (('en', 'English'), ('ru', 'Russian')):
        out = LOCALE_DIR / lang / 'LC_MESSAGES' / f'{DOMAIN}.po'
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(build_catalogue(lang, lang_name, msgids), encoding='utf-8')
        print(f"\nwrote {out.relative_to(Path(__file__).parent)} "
              f"({len(msgids)} entries)")

    print("\nNow run: python3 compile_translations.py")
    return 0


if __name__ == '__main__':
    sys.exit(main())
